# Generated by Django 3.2.4 on 2021-06-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookGenerationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('DONE_SUCCESS', 'Done Success'), ('DONE_FAILED', 'Done Failed')], max_length=16)),
                ('celery_task_id', models.UUIDField(editable=False, unique=True)),
                ('celery_group_id', models.UUIDField(editable=False, unique=True)),
            ],
        ),
    ]
