# Generated by Django 3.2.4 on 2021-06-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookgenerationtask',
            name='result_book',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bookgenerationtask',
            name='celery_group_id',
            field=models.UUIDField(blank=True),
        ),
        migrations.AlterField(
            model_name='bookgenerationtask',
            name='celery_task_id',
            field=models.UUIDField(blank=True),
        ),
    ]
