# Generated by Django 3.2.4 on 2021-06-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210621_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookgenerationtask',
            name='celery_group_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookgenerationtask',
            name='celery_task_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
